// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingCart.Data.Contexts;

#nullable disable

namespace ShoppingCart.Data.Migrations.ShoppingCartDb
{
    [DbContext(typeof(ShoppingCartDbContext))]
    [Migration("20240124163927_Add 100 Items")]
    partial class Add100Items
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShoppingCart.Models.DataModels.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "The Laptops and Computers Category.",
                            Name = "Laptops & Computers"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "The Appliance Category.",
                            Name = "Appliance"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "The TVs and Projectors Category.",
                            Name = "TVs & Projectors"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "The Cell Phones Category.",
                            Name = "Cell Phones"
                        });
                });

            modelBuilder.Entity("ShoppingCart.Models.DataModels.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryId = 1L,
                            Description = "Dell - Inspiron 16.0\" 2-in-1 OLED Touch Laptop - 13th Gen Intel Evo i7 - 16GB Memory - NVIDIA GeForce MX550 - 1TB SSD - Stylus - Dark River Blue",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6539/6539903_sd.jpg",
                            Name = "Dell - Inspiron 16.0\"",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 2L,
                            CategoryId = 2L,
                            Description = "Samsung - 6.3 cu. ft. Smart Instant Heat Slide-in Induction Range with Air Fry & Convection+ - Stainless Steel",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6491/6491829_sd.jpg",
                            Name = "Samsung - 6.3 Range",
                            Price = 1599.99m
                        },
                        new
                        {
                            Id = 3L,
                            CategoryId = 3L,
                            Description = "Samsung - 65” Class QN85C Neo QLED 4K UHD Smart Tizen TV",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6536/6536418_sd.jpg",
                            Name = "Samsung - 65\"",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryId = 4L,
                            Description = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525408_sd.jpg",
                            Name = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryId = 1L,
                            Description = "Dell - Inspiron 16.0\" 2-in-1 OLED Touch Laptop - 13th Gen Intel Evo i7 - 16GB Memory - NVIDIA GeForce MX550 - 1TB SSD - Stylus - Dark River Blue",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6539/6539903_sd.jpg",
                            Name = "Dell - Inspiron 16.0\"",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryId = 2L,
                            Description = "Samsung - 6.3 cu. ft. Smart Instant Heat Slide-in Induction Range with Air Fry & Convection+ - Stainless Steel",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6491/6491829_sd.jpg",
                            Name = "Samsung - 6.3 Range",
                            Price = 1599.99m
                        },
                        new
                        {
                            Id = 7L,
                            CategoryId = 3L,
                            Description = "Samsung - 65” Class QN85C Neo QLED 4K UHD Smart Tizen TV",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6536/6536418_sd.jpg",
                            Name = "Samsung - 65\"",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = 8L,
                            CategoryId = 4L,
                            Description = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525408_sd.jpg",
                            Name = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 9L,
                            CategoryId = 1L,
                            Description = "Dell - Inspiron 16.0\" 2-in-1 OLED Touch Laptop - 13th Gen Intel Evo i7 - 16GB Memory - NVIDIA GeForce MX550 - 1TB SSD - Stylus - Dark River Blue",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6539/6539903_sd.jpg",
                            Name = "Dell - Inspiron 16.0\"",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 10L,
                            CategoryId = 2L,
                            Description = "Samsung - 6.3 cu. ft. Smart Instant Heat Slide-in Induction Range with Air Fry & Convection+ - Stainless Steel",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6491/6491829_sd.jpg",
                            Name = "Samsung - 6.3 Range",
                            Price = 1599.99m
                        },
                        new
                        {
                            Id = 11L,
                            CategoryId = 3L,
                            Description = "Samsung - 65” Class QN85C Neo QLED 4K UHD Smart Tizen TV",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6536/6536418_sd.jpg",
                            Name = "Samsung - 65\"",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = 12L,
                            CategoryId = 4L,
                            Description = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525408_sd.jpg",
                            Name = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 13L,
                            CategoryId = 1L,
                            Description = "Dell - Inspiron 16.0\" 2-in-1 OLED Touch Laptop - 13th Gen Intel Evo i7 - 16GB Memory - NVIDIA GeForce MX550 - 1TB SSD - Stylus - Dark River Blue",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6539/6539903_sd.jpg",
                            Name = "Dell - Inspiron 16.0\"",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 14L,
                            CategoryId = 2L,
                            Description = "Samsung - 6.3 cu. ft. Smart Instant Heat Slide-in Induction Range with Air Fry & Convection+ - Stainless Steel",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6491/6491829_sd.jpg",
                            Name = "Samsung - 6.3 Range",
                            Price = 1599.99m
                        },
                        new
                        {
                            Id = 15L,
                            CategoryId = 3L,
                            Description = "Samsung - 65” Class QN85C Neo QLED 4K UHD Smart Tizen TV",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6536/6536418_sd.jpg",
                            Name = "Samsung - 65\"",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = 16L,
                            CategoryId = 4L,
                            Description = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525408_sd.jpg",
                            Name = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 17L,
                            CategoryId = 1L,
                            Description = "Dell - Inspiron 16.0\" 2-in-1 OLED Touch Laptop - 13th Gen Intel Evo i7 - 16GB Memory - NVIDIA GeForce MX550 - 1TB SSD - Stylus - Dark River Blue",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6539/6539903_sd.jpg",
                            Name = "Dell - Inspiron 16.0\"",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 18L,
                            CategoryId = 2L,
                            Description = "Samsung - 6.3 cu. ft. Smart Instant Heat Slide-in Induction Range with Air Fry & Convection+ - Stainless Steel",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6491/6491829_sd.jpg",
                            Name = "Samsung - 6.3 Range",
                            Price = 1599.99m
                        },
                        new
                        {
                            Id = 19L,
                            CategoryId = 3L,
                            Description = "Samsung - 65” Class QN85C Neo QLED 4K UHD Smart Tizen TV",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6536/6536418_sd.jpg",
                            Name = "Samsung - 65\"",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = 20L,
                            CategoryId = 4L,
                            Description = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525408_sd.jpg",
                            Name = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 21L,
                            CategoryId = 1L,
                            Description = "Dell - Inspiron 16.0\" 2-in-1 OLED Touch Laptop - 13th Gen Intel Evo i7 - 16GB Memory - NVIDIA GeForce MX550 - 1TB SSD - Stylus - Dark River Blue",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6539/6539903_sd.jpg",
                            Name = "Dell - Inspiron 16.0\"",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 22L,
                            CategoryId = 2L,
                            Description = "Samsung - 6.3 cu. ft. Smart Instant Heat Slide-in Induction Range with Air Fry & Convection+ - Stainless Steel",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6491/6491829_sd.jpg",
                            Name = "Samsung - 6.3 Range",
                            Price = 1599.99m
                        },
                        new
                        {
                            Id = 23L,
                            CategoryId = 3L,
                            Description = "Samsung - 65” Class QN85C Neo QLED 4K UHD Smart Tizen TV",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6536/6536418_sd.jpg",
                            Name = "Samsung - 65\"",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = 24L,
                            CategoryId = 4L,
                            Description = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525408_sd.jpg",
                            Name = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 25L,
                            CategoryId = 1L,
                            Description = "Dell - Inspiron 16.0\" 2-in-1 OLED Touch Laptop - 13th Gen Intel Evo i7 - 16GB Memory - NVIDIA GeForce MX550 - 1TB SSD - Stylus - Dark River Blue",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6539/6539903_sd.jpg",
                            Name = "Dell - Inspiron 16.0\"",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 26L,
                            CategoryId = 2L,
                            Description = "Samsung - 6.3 cu. ft. Smart Instant Heat Slide-in Induction Range with Air Fry & Convection+ - Stainless Steel",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6491/6491829_sd.jpg",
                            Name = "Samsung - 6.3 Range",
                            Price = 1599.99m
                        },
                        new
                        {
                            Id = 27L,
                            CategoryId = 3L,
                            Description = "Samsung - 65” Class QN85C Neo QLED 4K UHD Smart Tizen TV",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6536/6536418_sd.jpg",
                            Name = "Samsung - 65\"",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = 28L,
                            CategoryId = 4L,
                            Description = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525408_sd.jpg",
                            Name = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 29L,
                            CategoryId = 1L,
                            Description = "Dell - Inspiron 16.0\" 2-in-1 OLED Touch Laptop - 13th Gen Intel Evo i7 - 16GB Memory - NVIDIA GeForce MX550 - 1TB SSD - Stylus - Dark River Blue",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6539/6539903_sd.jpg",
                            Name = "Dell - Inspiron 16.0\"",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 30L,
                            CategoryId = 2L,
                            Description = "Samsung - 6.3 cu. ft. Smart Instant Heat Slide-in Induction Range with Air Fry & Convection+ - Stainless Steel",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6491/6491829_sd.jpg",
                            Name = "Samsung - 6.3 Range",
                            Price = 1599.99m
                        },
                        new
                        {
                            Id = 31L,
                            CategoryId = 3L,
                            Description = "Samsung - 65” Class QN85C Neo QLED 4K UHD Smart Tizen TV",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6536/6536418_sd.jpg",
                            Name = "Samsung - 65\"",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = 32L,
                            CategoryId = 4L,
                            Description = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525408_sd.jpg",
                            Name = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 33L,
                            CategoryId = 1L,
                            Description = "Dell - Inspiron 16.0\" 2-in-1 OLED Touch Laptop - 13th Gen Intel Evo i7 - 16GB Memory - NVIDIA GeForce MX550 - 1TB SSD - Stylus - Dark River Blue",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6539/6539903_sd.jpg",
                            Name = "Dell - Inspiron 16.0\"",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 34L,
                            CategoryId = 2L,
                            Description = "Samsung - 6.3 cu. ft. Smart Instant Heat Slide-in Induction Range with Air Fry & Convection+ - Stainless Steel",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6491/6491829_sd.jpg",
                            Name = "Samsung - 6.3 Range",
                            Price = 1599.99m
                        },
                        new
                        {
                            Id = 35L,
                            CategoryId = 3L,
                            Description = "Samsung - 65” Class QN85C Neo QLED 4K UHD Smart Tizen TV",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6536/6536418_sd.jpg",
                            Name = "Samsung - 65\"",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = 36L,
                            CategoryId = 4L,
                            Description = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525408_sd.jpg",
                            Name = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 37L,
                            CategoryId = 1L,
                            Description = "Dell - Inspiron 16.0\" 2-in-1 OLED Touch Laptop - 13th Gen Intel Evo i7 - 16GB Memory - NVIDIA GeForce MX550 - 1TB SSD - Stylus - Dark River Blue",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6539/6539903_sd.jpg",
                            Name = "Dell - Inspiron 16.0\"",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 38L,
                            CategoryId = 2L,
                            Description = "Samsung - 6.3 cu. ft. Smart Instant Heat Slide-in Induction Range with Air Fry & Convection+ - Stainless Steel",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6491/6491829_sd.jpg",
                            Name = "Samsung - 6.3 Range",
                            Price = 1599.99m
                        },
                        new
                        {
                            Id = 39L,
                            CategoryId = 3L,
                            Description = "Samsung - 65” Class QN85C Neo QLED 4K UHD Smart Tizen TV",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6536/6536418_sd.jpg",
                            Name = "Samsung - 65\"",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = 40L,
                            CategoryId = 4L,
                            Description = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525408_sd.jpg",
                            Name = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 41L,
                            CategoryId = 1L,
                            Description = "Dell - Inspiron 16.0\" 2-in-1 OLED Touch Laptop - 13th Gen Intel Evo i7 - 16GB Memory - NVIDIA GeForce MX550 - 1TB SSD - Stylus - Dark River Blue",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6539/6539903_sd.jpg",
                            Name = "Dell - Inspiron 16.0\"",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 42L,
                            CategoryId = 2L,
                            Description = "Samsung - 6.3 cu. ft. Smart Instant Heat Slide-in Induction Range with Air Fry & Convection+ - Stainless Steel",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6491/6491829_sd.jpg",
                            Name = "Samsung - 6.3 Range",
                            Price = 1599.99m
                        },
                        new
                        {
                            Id = 43L,
                            CategoryId = 3L,
                            Description = "Samsung - 65” Class QN85C Neo QLED 4K UHD Smart Tizen TV",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6536/6536418_sd.jpg",
                            Name = "Samsung - 65\"",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = 44L,
                            CategoryId = 4L,
                            Description = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525408_sd.jpg",
                            Name = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 45L,
                            CategoryId = 1L,
                            Description = "Dell - Inspiron 16.0\" 2-in-1 OLED Touch Laptop - 13th Gen Intel Evo i7 - 16GB Memory - NVIDIA GeForce MX550 - 1TB SSD - Stylus - Dark River Blue",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6539/6539903_sd.jpg",
                            Name = "Dell - Inspiron 16.0\"",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 46L,
                            CategoryId = 2L,
                            Description = "Samsung - 6.3 cu. ft. Smart Instant Heat Slide-in Induction Range with Air Fry & Convection+ - Stainless Steel",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6491/6491829_sd.jpg",
                            Name = "Samsung - 6.3 Range",
                            Price = 1599.99m
                        },
                        new
                        {
                            Id = 47L,
                            CategoryId = 3L,
                            Description = "Samsung - 65” Class QN85C Neo QLED 4K UHD Smart Tizen TV",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6536/6536418_sd.jpg",
                            Name = "Samsung - 65\"",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = 48L,
                            CategoryId = 4L,
                            Description = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525408_sd.jpg",
                            Name = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 49L,
                            CategoryId = 1L,
                            Description = "Dell - Inspiron 16.0\" 2-in-1 OLED Touch Laptop - 13th Gen Intel Evo i7 - 16GB Memory - NVIDIA GeForce MX550 - 1TB SSD - Stylus - Dark River Blue",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6539/6539903_sd.jpg",
                            Name = "Dell - Inspiron 16.0\"",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 50L,
                            CategoryId = 2L,
                            Description = "Samsung - 6.3 cu. ft. Smart Instant Heat Slide-in Induction Range with Air Fry & Convection+ - Stainless Steel",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6491/6491829_sd.jpg",
                            Name = "Samsung - 6.3 Range",
                            Price = 1599.99m
                        },
                        new
                        {
                            Id = 51L,
                            CategoryId = 3L,
                            Description = "Samsung - 65” Class QN85C Neo QLED 4K UHD Smart Tizen TV",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6536/6536418_sd.jpg",
                            Name = "Samsung - 65\"",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = 52L,
                            CategoryId = 4L,
                            Description = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525408_sd.jpg",
                            Name = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 53L,
                            CategoryId = 1L,
                            Description = "Dell - Inspiron 16.0\" 2-in-1 OLED Touch Laptop - 13th Gen Intel Evo i7 - 16GB Memory - NVIDIA GeForce MX550 - 1TB SSD - Stylus - Dark River Blue",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6539/6539903_sd.jpg",
                            Name = "Dell - Inspiron 16.0\"",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 54L,
                            CategoryId = 2L,
                            Description = "Samsung - 6.3 cu. ft. Smart Instant Heat Slide-in Induction Range with Air Fry & Convection+ - Stainless Steel",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6491/6491829_sd.jpg",
                            Name = "Samsung - 6.3 Range",
                            Price = 1599.99m
                        },
                        new
                        {
                            Id = 55L,
                            CategoryId = 3L,
                            Description = "Samsung - 65” Class QN85C Neo QLED 4K UHD Smart Tizen TV",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6536/6536418_sd.jpg",
                            Name = "Samsung - 65\"",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = 56L,
                            CategoryId = 4L,
                            Description = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525408_sd.jpg",
                            Name = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 57L,
                            CategoryId = 1L,
                            Description = "Dell - Inspiron 16.0\" 2-in-1 OLED Touch Laptop - 13th Gen Intel Evo i7 - 16GB Memory - NVIDIA GeForce MX550 - 1TB SSD - Stylus - Dark River Blue",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6539/6539903_sd.jpg",
                            Name = "Dell - Inspiron 16.0\"",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 58L,
                            CategoryId = 2L,
                            Description = "Samsung - 6.3 cu. ft. Smart Instant Heat Slide-in Induction Range with Air Fry & Convection+ - Stainless Steel",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6491/6491829_sd.jpg",
                            Name = "Samsung - 6.3 Range",
                            Price = 1599.99m
                        },
                        new
                        {
                            Id = 59L,
                            CategoryId = 3L,
                            Description = "Samsung - 65” Class QN85C Neo QLED 4K UHD Smart Tizen TV",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6536/6536418_sd.jpg",
                            Name = "Samsung - 65\"",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = 60L,
                            CategoryId = 4L,
                            Description = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525408_sd.jpg",
                            Name = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 61L,
                            CategoryId = 1L,
                            Description = "Dell - Inspiron 16.0\" 2-in-1 OLED Touch Laptop - 13th Gen Intel Evo i7 - 16GB Memory - NVIDIA GeForce MX550 - 1TB SSD - Stylus - Dark River Blue",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6539/6539903_sd.jpg",
                            Name = "Dell - Inspiron 16.0\"",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 62L,
                            CategoryId = 2L,
                            Description = "Samsung - 6.3 cu. ft. Smart Instant Heat Slide-in Induction Range with Air Fry & Convection+ - Stainless Steel",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6491/6491829_sd.jpg",
                            Name = "Samsung - 6.3 Range",
                            Price = 1599.99m
                        },
                        new
                        {
                            Id = 63L,
                            CategoryId = 3L,
                            Description = "Samsung - 65” Class QN85C Neo QLED 4K UHD Smart Tizen TV",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6536/6536418_sd.jpg",
                            Name = "Samsung - 65\"",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = 64L,
                            CategoryId = 4L,
                            Description = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525408_sd.jpg",
                            Name = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 65L,
                            CategoryId = 1L,
                            Description = "Dell - Inspiron 16.0\" 2-in-1 OLED Touch Laptop - 13th Gen Intel Evo i7 - 16GB Memory - NVIDIA GeForce MX550 - 1TB SSD - Stylus - Dark River Blue",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6539/6539903_sd.jpg",
                            Name = "Dell - Inspiron 16.0\"",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 66L,
                            CategoryId = 2L,
                            Description = "Samsung - 6.3 cu. ft. Smart Instant Heat Slide-in Induction Range with Air Fry & Convection+ - Stainless Steel",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6491/6491829_sd.jpg",
                            Name = "Samsung - 6.3 Range",
                            Price = 1599.99m
                        },
                        new
                        {
                            Id = 67L,
                            CategoryId = 3L,
                            Description = "Samsung - 65” Class QN85C Neo QLED 4K UHD Smart Tizen TV",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6536/6536418_sd.jpg",
                            Name = "Samsung - 65\"",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = 68L,
                            CategoryId = 4L,
                            Description = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525408_sd.jpg",
                            Name = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 69L,
                            CategoryId = 1L,
                            Description = "Dell - Inspiron 16.0\" 2-in-1 OLED Touch Laptop - 13th Gen Intel Evo i7 - 16GB Memory - NVIDIA GeForce MX550 - 1TB SSD - Stylus - Dark River Blue",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6539/6539903_sd.jpg",
                            Name = "Dell - Inspiron 16.0\"",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 70L,
                            CategoryId = 2L,
                            Description = "Samsung - 6.3 cu. ft. Smart Instant Heat Slide-in Induction Range with Air Fry & Convection+ - Stainless Steel",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6491/6491829_sd.jpg",
                            Name = "Samsung - 6.3 Range",
                            Price = 1599.99m
                        },
                        new
                        {
                            Id = 71L,
                            CategoryId = 3L,
                            Description = "Samsung - 65” Class QN85C Neo QLED 4K UHD Smart Tizen TV",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6536/6536418_sd.jpg",
                            Name = "Samsung - 65\"",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = 72L,
                            CategoryId = 4L,
                            Description = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525408_sd.jpg",
                            Name = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 73L,
                            CategoryId = 1L,
                            Description = "Dell - Inspiron 16.0\" 2-in-1 OLED Touch Laptop - 13th Gen Intel Evo i7 - 16GB Memory - NVIDIA GeForce MX550 - 1TB SSD - Stylus - Dark River Blue",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6539/6539903_sd.jpg",
                            Name = "Dell - Inspiron 16.0\"",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 74L,
                            CategoryId = 2L,
                            Description = "Samsung - 6.3 cu. ft. Smart Instant Heat Slide-in Induction Range with Air Fry & Convection+ - Stainless Steel",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6491/6491829_sd.jpg",
                            Name = "Samsung - 6.3 Range",
                            Price = 1599.99m
                        },
                        new
                        {
                            Id = 75L,
                            CategoryId = 3L,
                            Description = "Samsung - 65” Class QN85C Neo QLED 4K UHD Smart Tizen TV",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6536/6536418_sd.jpg",
                            Name = "Samsung - 65\"",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = 76L,
                            CategoryId = 4L,
                            Description = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525408_sd.jpg",
                            Name = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 77L,
                            CategoryId = 1L,
                            Description = "Dell - Inspiron 16.0\" 2-in-1 OLED Touch Laptop - 13th Gen Intel Evo i7 - 16GB Memory - NVIDIA GeForce MX550 - 1TB SSD - Stylus - Dark River Blue",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6539/6539903_sd.jpg",
                            Name = "Dell - Inspiron 16.0\"",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 78L,
                            CategoryId = 2L,
                            Description = "Samsung - 6.3 cu. ft. Smart Instant Heat Slide-in Induction Range with Air Fry & Convection+ - Stainless Steel",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6491/6491829_sd.jpg",
                            Name = "Samsung - 6.3 Range",
                            Price = 1599.99m
                        },
                        new
                        {
                            Id = 79L,
                            CategoryId = 3L,
                            Description = "Samsung - 65” Class QN85C Neo QLED 4K UHD Smart Tizen TV",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6536/6536418_sd.jpg",
                            Name = "Samsung - 65\"",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = 80L,
                            CategoryId = 4L,
                            Description = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525408_sd.jpg",
                            Name = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 81L,
                            CategoryId = 1L,
                            Description = "Dell - Inspiron 16.0\" 2-in-1 OLED Touch Laptop - 13th Gen Intel Evo i7 - 16GB Memory - NVIDIA GeForce MX550 - 1TB SSD - Stylus - Dark River Blue",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6539/6539903_sd.jpg",
                            Name = "Dell - Inspiron 16.0\"",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 82L,
                            CategoryId = 2L,
                            Description = "Samsung - 6.3 cu. ft. Smart Instant Heat Slide-in Induction Range with Air Fry & Convection+ - Stainless Steel",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6491/6491829_sd.jpg",
                            Name = "Samsung - 6.3 Range",
                            Price = 1599.99m
                        },
                        new
                        {
                            Id = 83L,
                            CategoryId = 3L,
                            Description = "Samsung - 65” Class QN85C Neo QLED 4K UHD Smart Tizen TV",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6536/6536418_sd.jpg",
                            Name = "Samsung - 65\"",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = 84L,
                            CategoryId = 4L,
                            Description = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525408_sd.jpg",
                            Name = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 85L,
                            CategoryId = 1L,
                            Description = "Dell - Inspiron 16.0\" 2-in-1 OLED Touch Laptop - 13th Gen Intel Evo i7 - 16GB Memory - NVIDIA GeForce MX550 - 1TB SSD - Stylus - Dark River Blue",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6539/6539903_sd.jpg",
                            Name = "Dell - Inspiron 16.0\"",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 86L,
                            CategoryId = 2L,
                            Description = "Samsung - 6.3 cu. ft. Smart Instant Heat Slide-in Induction Range with Air Fry & Convection+ - Stainless Steel",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6491/6491829_sd.jpg",
                            Name = "Samsung - 6.3 Range",
                            Price = 1599.99m
                        },
                        new
                        {
                            Id = 87L,
                            CategoryId = 3L,
                            Description = "Samsung - 65” Class QN85C Neo QLED 4K UHD Smart Tizen TV",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6536/6536418_sd.jpg",
                            Name = "Samsung - 65\"",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = 88L,
                            CategoryId = 4L,
                            Description = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525408_sd.jpg",
                            Name = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 89L,
                            CategoryId = 1L,
                            Description = "Dell - Inspiron 16.0\" 2-in-1 OLED Touch Laptop - 13th Gen Intel Evo i7 - 16GB Memory - NVIDIA GeForce MX550 - 1TB SSD - Stylus - Dark River Blue",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6539/6539903_sd.jpg",
                            Name = "Dell - Inspiron 16.0\"",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 90L,
                            CategoryId = 2L,
                            Description = "Samsung - 6.3 cu. ft. Smart Instant Heat Slide-in Induction Range with Air Fry & Convection+ - Stainless Steel",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6491/6491829_sd.jpg",
                            Name = "Samsung - 6.3 Range",
                            Price = 1599.99m
                        },
                        new
                        {
                            Id = 91L,
                            CategoryId = 3L,
                            Description = "Samsung - 65” Class QN85C Neo QLED 4K UHD Smart Tizen TV",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6536/6536418_sd.jpg",
                            Name = "Samsung - 65\"",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = 92L,
                            CategoryId = 4L,
                            Description = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525408_sd.jpg",
                            Name = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 93L,
                            CategoryId = 1L,
                            Description = "Dell - Inspiron 16.0\" 2-in-1 OLED Touch Laptop - 13th Gen Intel Evo i7 - 16GB Memory - NVIDIA GeForce MX550 - 1TB SSD - Stylus - Dark River Blue",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6539/6539903_sd.jpg",
                            Name = "Dell - Inspiron 16.0\"",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 94L,
                            CategoryId = 2L,
                            Description = "Samsung - 6.3 cu. ft. Smart Instant Heat Slide-in Induction Range with Air Fry & Convection+ - Stainless Steel",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6491/6491829_sd.jpg",
                            Name = "Samsung - 6.3 Range",
                            Price = 1599.99m
                        },
                        new
                        {
                            Id = 95L,
                            CategoryId = 3L,
                            Description = "Samsung - 65” Class QN85C Neo QLED 4K UHD Smart Tizen TV",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6536/6536418_sd.jpg",
                            Name = "Samsung - 65\"",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = 96L,
                            CategoryId = 4L,
                            Description = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525408_sd.jpg",
                            Name = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 97L,
                            CategoryId = 1L,
                            Description = "Dell - Inspiron 16.0\" 2-in-1 OLED Touch Laptop - 13th Gen Intel Evo i7 - 16GB Memory - NVIDIA GeForce MX550 - 1TB SSD - Stylus - Dark River Blue",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6539/6539903_sd.jpg",
                            Name = "Dell - Inspiron 16.0\"",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 98L,
                            CategoryId = 2L,
                            Description = "Samsung - 6.3 cu. ft. Smart Instant Heat Slide-in Induction Range with Air Fry & Convection+ - Stainless Steel",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6491/6491829_sd.jpg",
                            Name = "Samsung - 6.3 Range",
                            Price = 1599.99m
                        },
                        new
                        {
                            Id = 99L,
                            CategoryId = 3L,
                            Description = "Samsung - 65” Class QN85C Neo QLED 4K UHD Smart Tizen TV",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6536/6536418_sd.jpg",
                            Name = "Samsung - 65\"",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = 100L,
                            CategoryId = 4L,
                            Description = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525408_sd.jpg",
                            Name = "Apple - iPhone 15 Pro 256GB - Black Titanium",
                            Price = 1099.99m
                        });
                });

            modelBuilder.Entity("ShoppingCart.Models.DataModels.Item", b =>
                {
                    b.HasOne("ShoppingCart.Models.DataModels.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ShoppingCart.Models.DataModels.Category", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
