// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingCart.Data.Contexts;

#nullable disable

namespace ShoppingCart.Data.Migrations.ShoppingCartDb
{
    [DbContext(typeof(ShoppingCartDbContext))]
    [Migration("20240123014323_CreateTables(Items,Categories)")]
    partial class CreateTablesItemsCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShoppingCart.Data.Models.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "The Laptops and Computers Category.",
                            Name = "Laptops & Computers"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "The Appliance Category.",
                            Name = "Appliance"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "The TVs and Projectors Category.",
                            Name = "TVs & Projectors"
                        });
                });

            modelBuilder.Entity("ShoppingCart.Data.Models.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryId = 1L,
                            Description = "Dell - Inspiron 16.0\" 2-in-1 OLED Touch Laptop - 13th Gen Intel Evo i7 - 16GB Memory - NVIDIA GeForce MX550 - 1TB SSD - Stylus - Dark River Blue",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6539/6539903_sd.jpg",
                            Name = "Dell - Inspiron 16.0\"",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 2L,
                            CategoryId = 2L,
                            Description = "Samsung - 6.3 cu. ft. Smart Instant Heat Slide-in Induction Range with Air Fry & Convection+ - Stainless Steel",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6491/6491829_sd.jpg",
                            Name = "Samsung - 6.3 Range",
                            Price = 1599.99m
                        },
                        new
                        {
                            Id = 3L,
                            CategoryId = 3L,
                            Description = "Samsung - 65” Class QN85C Neo QLED 4K UHD Smart Tizen TV",
                            ImagePath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6536/6536418_sd.jpg",
                            Name = "Samsung - 65\"",
                            Price = 1299.99m
                        });
                });

            modelBuilder.Entity("ShoppingCart.Data.Models.Item", b =>
                {
                    b.HasOne("ShoppingCart.Data.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ShoppingCart.Data.Models.Category", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
